package artificialMiner.nodes;


import artificialMiner.artificialMiner;
import org.shadowbot.bot.api.wrapper.Area;
import org.shadowbot.bot.api.wrapper.Tile;

import javax.swing.*;

/**
 * @author Pen
 */
public class Gui2 extends javax.swing.JFrame {

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;

    /**
     * Creates new form fighterGUI
     */
    public Gui2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Start!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("ArtificalFighter");

        jRadioButton1.setText("Banking");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("drop");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Choose Location", "Varrock East"}));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Choose Rock", "Copper", "Tin", "Clay", "Iron", "Coal"}));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel6)
                                .addContainerGap(35, Short.MAX_VALUE))
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton1)
                                .addContainerGap())
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jRadioButton2)
                                        .addComponent(jRadioButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (jComboBox1.getSelectedItem() == "Varrock East") {
            jComboBox1.setModel(new DefaultComboBoxModel(new String[]{
                    "Clay", "Copper", "Tin", "Iron"
            }));
            artificialMiner.bankTile = new Tile(3254, 3420);
            artificialMiner.bankArea = new Area(new Tile(3250, 3419), new Tile(3257, 3423));
            if (jComboBox2.equals("Copper") || jComboBox2.equals("Tin")) {
                artificialMiner.mineTile = new Tile(3285, 3363);
            } else {
                artificialMiner.mineTile = new Tile(3286, 3370);
            }
            artificialMiner.mineArea = new Area(new Tile(3279, 3358), new Tile(3292, 3372));
        }

        String str = jComboBox2.getSelectedItem().toString();
        if (str.equals("Copper")) {
            artificialMiner.toMine = new int[]{2551, 2550};
            artificialMiner.drop = 436;
            artificialMiner.toMines = "Copper";
        } else {
            if (str.equals("Tin")) {
                artificialMiner.toMine = new int[]{13717, 13718};
                artificialMiner.drop = 438;
                artificialMiner.toMines = "Tin";
            } else {
                if (str.equals("Clay")) {
                    artificialMiner.toMine = new int[]{1, 2, 3};
                    artificialMiner.drop = 434;
                } else {
                    if (str.equals("Silver")) {
                        artificialMiner.toMine = new int[]{1, 2, 3};
                        artificialMiner.drop = 0;
                    } else {
                        if (str.equals("Iron")) {
                            artificialMiner.toMine = new int[]{1, 2, 3};
                            artificialMiner.drop = 440;
                        } else {
                            if (str.equals("Coal")) {
                                artificialMiner.toMine = new int[]{1, 2, 3};
                                artificialMiner.drop = 0;
                            } else {
                                if (str.equals("Gold")) {
                                    artificialMiner.toMine = new int[]{1, 2, 3};
                                    artificialMiner.drop = 0;
                                } else {
                                    if (str.equals("Mithril")) {
                                        artificialMiner.toMine = new int[]{1, 2, 3};
                                        artificialMiner.drop = 0;
                                    } else {
                                        if (str.equals("Adamante")) {
                                            artificialMiner.toMine = new int[]{1, 2, 3};
                                            artificialMiner.drop = 0;
                                        } else {
                                            if (str.equals("Runite")) {
                                                artificialMiner.toMine = new int[]{1, 2, 3};
                                                artificialMiner.drop = 0;
                                            }

                                        }
                                    }
                                }
                            }
                        }
                    }
                }

            }
        }

        artificialMiner.guiStart = false;
        dispose();
    }

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (jRadioButton2.isSelected()) {
            artificialMiner.banking = false;
            jComboBox1.disable();
            jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(
                    new String[]{
                            "Copper",
                            "Tin",
                            "Clay",
                            "Iron",
                            "Silver",
                            "Coal",
                            "Gold",
                            "Mithril",
                            "Adamante",
                            "Runite"}));
        }
    }

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        if (jRadioButton1.isSelected()) {
            artificialMiner.banking = true;
        }
    }
    // End of variables declaration
}
